server:
  port: 8764

spring:
  application:
    name: service-hi

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#      defaultZone: http://peer1:1111/eureka/,http://peer2:1112/eureka/
